AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - tmp/**/*
    - db/**/*
    - bin/**/*

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
